name: Deploy Windows Dev

on:
  push:
    tags:
      - 'dev-*'

#for uploading release exe
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install
      - run: yarn workspace nt-app electron:build --publish never
      - run: ls ${{ github.workspace }}/nt-app/dist_electron/
      - run: |
          mkdir ${{ github.workspace }}/build
          cp "${{ github.workspace }}/nt-app/dist_electron/latest.yml" ${{ github.workspace }}/build/latest.yml
          cp "${{ github.workspace }}/nt-app/dist_electron/Noita-Together-Setup-*.exe" ${{ github.workspace }}/build/
          cp "${{ github.workspace }}/nt-app/dist_electron/Noita-Together-Setup-*.exe.blockmap" ${{ github.workspace }}/build/
      - name: Upload files to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/build/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
